# Generated by Django 4.2.7 on 2023-12-04 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_title', models.BinaryField(default=b'gAAAAABlbghSKYS2Se4L3ARNE6_8M2uu6Bu9NORO7b7YObO8CxrSjTvRyjm60aVPmNy5H1GPLfLyMxZPur6rJagwTNBJJkubbw==')),
                ('encrypted_description', models.BinaryField(default=b'gAAAAABlbghSN7kQzo0tfyKml-0Fq0rXKEcxBKSI3YFFs15q6-Vi5TMsDr6lPONScS4T4NsAxuwaV4FV4KbEQc0E2LeO_8XtykKfzZ0Ztmg0rOsCkZ31vU4=')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
