# Generated by Django 4.2.7 on 2023-11-10 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_responsible', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('job_position', models.CharField(choices=[('architect', 'Architecte Logiciel'), ('functional_analyst', 'Analyste Fonctionnel'), ('mission_leader', 'Chef de Mission'), ('project_manager', 'Chef de Projet'), ('developer', 'Développeur'), ('tester', 'Testeur'), ('app_maintenance', 'Maintenance Applicative'), ('project_specialist', 'Spécialiste en Gestion de Projet')], max_length=50)),
                ('grade', models.CharField(choices=[('senior_engineer', 'Ingénieur Principal'), ('lead_engineer', 'Ingénieur Major'), ('junior_engineer', 'Ingénieur Junior'), ('technician', 'Technicien')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
